import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Prismic from 'prismic-javascript'

export default function Home(props) {
  
  const {resultados} = props

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {resultados.map((imagens) => (        
        <img src={imagens.data.fotos.url}/>
      ))}

    </div>
  )
}

export async function getServerSideProps({res}){
  const client = await Prismic.client('https://brunoangeloti.prismic.io/api/v2')
  const img = await client.query(Prismic.Predicates.at('document.type', 'photosgal'))
  return{
    props:{
      resultados: img.results
    }
  }
}
